const DATA=[
{id:'day1',label:'Jour 1',title:'Jour 1 – Mercredi 29/07 · Pontarlier → Dongo',tags:['Route alpine','Installation camping','Balade Dongo'],note:'Objectif : arriver sans stress, s’installer, puis découvrir Dongo tranquillement en soirée.',steps:[
{id:'j1-1',time:'07:30',title:'Départ de Pontarlier',meta:'Prévoir papiers, assurance, carte bancaire, eau, pique-nique ou pause.',actions:[['Itinéraire complet','https://www.google.com/maps/dir/Pontarlier/Camping+Magic+Lake+Dongo','map']]},
{id:'j1-2',time:'10:45',title:'Pause Simplon / Suisse',meta:'Pause courte conseillée avant la descente vers l’Italie.',actions:[['GPS Simplon','https://maps.google.com/?q=Simplon+Pass','map']],tour:'simplon'},
{id:'j1-3',time:'12:30',title:'Pause à Domodossola',meta:'Ville agréable pour couper la route. Parking proche de la Piazza Mercato.',actions:[['Parking','https://maps.google.com/?q=Parcheggio+Piazza+Mercato+Domodossola','map']],tour:'domodossola'},
{id:'j1-4',time:'16:00',title:'Arrivée Camping Magic Lake',meta:'Via Vigna del Lago 60, 22014 Dongo CO. Installation et repérage.',actions:[['GPS camping','https://maps.google.com/?q=Camping+Magic+Lake+Via+Vigna+del+Lago+60+Dongo','map'],['Site camping','https://www.magiclake.it/','site']]},
{id:'j1-5',time:'18:15',title:'Balade à Dongo',meta:'Front de lac, vieux port, centre historique.',actions:[['Centre de Dongo','https://maps.google.com/?q=Dongo+CO+Italy','map']],tour:'dongo'}]},
{id:'day2',label:'Jour 2',title:'Jour 2 – Jeudi 30/07 · Triangle d’or',tags:['Menaggio','Ferry','Varenna','Bellagio'],note:'Se garer une fois à Menaggio, puis utiliser les ferries piétons.',steps:[
{id:'j2-1',time:'08:15',title:'Départ camping → Menaggio',meta:'Trajet env. 25–35 min.',actions:[['Itinéraire','https://www.google.com/maps/dir/Camping+Magic+Lake+Dongo/Menaggio','map']]},
{id:'j2-2',time:'08:50',title:'Parking Menaggio',meta:'Parking pratique près du centre/embarcadère. Prévoir quelques euros.',actions:[['GPS parking','https://maps.google.com/?q=Parcheggio+Menaggio+imbarcadero','map']]},
{id:'j2-3',time:'09:30',title:'Ferry Menaggio → Varenna',meta:'Arriver 15–20 min avant. Vérifier les horaires la veille.',actions:[['Embarcadère','https://maps.google.com/?q=Menaggio+Ferry+Terminal','map'],['Horaires ferry','https://www.navigazionelaghi.it/en/tickets-and-timetables-lake-como/','site']],tour:'ferry'},
{id:'j2-4',time:'10:00',title:'Varenna',meta:'Village de pêcheurs, ruelles, Passeggiata degli Innamorati.',actions:[['GPS','https://maps.google.com/?q=Varenna','map']],tour:'varenna'},
{id:'j2-5',time:'11:30',title:'Villa Monastero',meta:'Ancien monastère devenu villa-musée avec jardins.',actions:[['GPS','https://maps.google.com/?q=Villa+Monastero+Varenna','map'],['Site','https://www.villamonastero.eu/','site']],tour:'monastero'},
{id:'j2-6',time:'15:00',title:'Bellagio',meta:'Centre historique, ruelles en escalier, basilique San Giacomo.',actions:[['GPS','https://maps.google.com/?q=Bellagio+Lake+Como','map']],tour:'bellagio'},
{id:'j2-7',time:'16:30',title:'Jardins de la Villa Melzi',meta:'Jardins historiques du XIXe siècle.',actions:[['GPS','https://maps.google.com/?q=Villa+Melzi+Bellagio','map'],['Site','https://giardinidivillamelzi.it/en/','site']],tour:'melzi'}]},
{id:'day3',label:'Jour 3',title:'Jour 3 – Vendredi 31/07 · Lenno, Balbianello & Tremezzo',tags:['Villa del Balbianello','Greenway','Villa Carlotta option'],note:'Journée “rive ouest noble” : villas, jardins et promenade.',steps:[
{id:'j3-1',time:'08:15',title:'Départ camping → Lenno',meta:'Durée indicative : 40–55 min.',actions:[['Itinéraire','https://www.google.com/maps/dir/Camping+Magic+Lake+Dongo/Lenno+Tremezzina','map']]},
{id:'j3-2',time:'09:10',title:'Parking Lenno',meta:'Se garer près du Lido / centre de Lenno. Prévoir parking payant.',actions:[['GPS parking','https://maps.google.com/?q=Parcheggio+Lenno+Villa+del+Balbianello','map']]},
{id:'j3-3',time:'10:00',title:'Villa del Balbianello',meta:'Réservation fortement conseillée. Temps conseillé : 1h30 à 2h.',actions:[['GPS','https://maps.google.com/?q=Villa+del+Balbianello','map'],['Billets','https://fondoambiente.it/villa-del-balbianello-eng','site']],tour:'balbianello'},
{id:'j3-4',time:'14:00',title:'Greenway Lenno → Tremezzo',meta:'Balade facile sur une portion de la Greenway del Lago di Como.',actions:[['GPS','https://maps.google.com/?q=Greenway+del+Lago+di+Como+Lenno+Tremezzo','map'],['Site','https://greenwaylagodicomo.com/en/','site']],tour:'greenway'},
{id:'j3-5',time:'15:15',title:'Option Villa Carlotta',meta:'Très belle option si vous avez envie d’une seconde villa.',actions:[['GPS','https://maps.google.com/?q=Villa+Carlotta+Tremezzo','map'],['Site','https://www.villacarlotta.it/en/visit/','site']],tour:'carlotta'}]},
{id:'day4',label:'Jour 4',title:'Jour 4 – Samedi 01/08 · Gravedona, Piona & détente',tags:['Gravedona','Abbaye de Piona','Détente lac'],note:'Dernière journée complète volontairement plus calme.',steps:[
{id:'j4-1',time:'09:00',title:'Départ camping → Gravedona',meta:'Trajet très court : environ 5–10 min.',actions:[['Itinéraire','https://www.google.com/maps/dir/Camping+Magic+Lake+Dongo/Gravedona+ed+Uniti','map']]},
{id:'j4-2',time:'09:15',title:'Parking Gravedona',meta:'Se garer près du front de lac ou du centre.',actions:[['GPS parking','https://maps.google.com/?q=Parcheggio+Gravedona+lungolago','map']]},
{id:'j4-3',time:'09:30',title:'Gravedona – vieille ville & front de lac',meta:'Promenade du lac, ruelles, port, ambiance plus locale.',actions:[['Centre','https://maps.google.com/?q=Gravedona+ed+Uniti+old+town','map']],tour:'gravedona'},
{id:'j4-4',time:'10:45',title:'Basilique Santa Maria del Tiglio',meta:'Église romane emblématique du nord du lac.',actions:[['GPS basilique','https://maps.google.com/?q=Santa+Maria+del+Tiglio+Gravedona','map']],tour:'tiglio'},
{id:'j4-5',time:'11:45',title:'Route vers Abbaye de Piona',meta:'Trajet indicatif : 20–30 min.',actions:[['Itinéraire','https://www.google.com/maps/dir/Gravedona+ed+Uniti/Abbazia+di+Piona','map']]},
{id:'j4-6',time:'12:15',title:'Abbaye de Piona',meta:'Cloître, église, panorama, boutique monastique.',actions:[['GPS abbaye','https://maps.google.com/?q=Abbazia+di+Piona','map']],tour:'piona'},
{id:'j4-7',time:'15:30',title:'Après-midi détente au camping / lac',meta:'Baignade, repos, balade sur le front de lac, paddle si disponible.',actions:[['Retour camping','https://maps.google.com/?q=Camping+Magic+Lake+Dongo','map']]}]},
{id:'day5',label:'Jour 5',title:'Jour 5 – Dimanche 02/08 · Retour par Aoste',tags:['Fort de Bard','Aoste','Grand-Saint-Bernard','Pontarlier'],note:'Retour transformé en road-trip.',steps:[
{id:'j5-1',time:'08:00',title:'Départ Camping Magic Lake',meta:'Faire le plein si besoin, préparer eau et encas.',actions:[['Itinéraire complet','https://www.google.com/maps/dir/Camping+Magic+Lake+Dongo/Fort+of+Bard/Aosta/Pontarlier','map']]},
{id:'j5-2',time:'10:45',title:'Fort de Bard',meta:'Prévoir environ 1h à 1h30 sur place.',actions:[['GPS parking','https://maps.google.com/?q=Fort+of+Bard+parking','map'],['Site officiel','https://www.fortedibard.it/en/','site']],tour:'bard'},
{id:'j5-3',time:'12:15',title:'Route Fort de Bard → Aoste',meta:'Trajet indicatif : 35–45 min.',actions:[['Itinéraire','https://www.google.com/maps/dir/Fort+of+Bard/Aosta','map']]},
{id:'j5-4',time:'13:00',title:'Parking Aoste',meta:'Privilégier un grand parking proche du centre.',actions:[['Parking de la Ville','https://maps.google.com/?q=Parcheggio+de+la+Ville+Aosta','map']]},
{id:'j5-5',time:'14:30',title:'Aoste – parcours romain à pied',meta:'Arc d’Auguste, Porta Praetoria, théâtre romain, centre piéton.',actions:[['Théâtre romain','https://maps.google.com/?q=Aosta+Roman+Theatre','map']],tour:'aosta'},
{id:'j5-6',time:'16:30',title:'Départ Aoste → Grand-Saint-Bernard',meta:'Col si météo favorable, tunnel si vous voulez gagner du temps.',actions:[['Option col','https://www.google.com/maps/dir/Aosta/Great+St+Bernard+Pass/Pontarlier','map'],['Option tunnel','https://www.google.com/maps/dir/Aosta/Great+St+Bernard+Tunnel/Pontarlier','map']],tour:'gsb'}]}];
const TOURS={simplon:{title:'Le Simplon',intro:'Grand passage entre Suisse et Italie.',blocks:['Le Simplon marque la transition entre l’ambiance alpine suisse et les vallées italiennes.']},domodossola:{title:'Domodossola',intro:'Porte italienne des Alpes.',blocks:['La Piazza Mercato, ses arcades et les ruelles du centre donnent une première vraie ambiance italienne.']},dongo:{title:'Dongo',intro:'Village du haut lac et mémoire de 1945.',blocks:['Dongo est lié à la fin de la Seconde Guerre mondiale : Mussolini fut capturé dans la région le 27 avril 1945.']},ferry:{title:'Les ferries du centre du lac',intro:'Relier Menaggio, Varenna et Bellagio.',blocks:['Le ferry évite les routes étroites et les parkings compliqués.']},varenna:{title:'Varenna',intro:'Ancien village de pêcheurs.',blocks:['Varenna se découvre à pied : port, ruelles, Passeggiata degli Innamorati et vues vers Bellagio.']},monastero:{title:'Villa Monastero',intro:'Ancien monastère devenu villa-musée.',blocks:['Les jardins longent le lac avec terrasses, essences exotiques et vues sur le centre du lac.']},bellagio:{title:'Bellagio',intro:'La perle du lac.',blocks:['Bellagio occupe une position exceptionnelle au point où les branches du lac se rejoignent.']},melzi:{title:'Jardins de la Villa Melzi',intro:'Élégance romantique du XIXe siècle.',blocks:['Ces jardins offrent une promenade douce au bord de l’eau.']},balbianello:{title:'Villa del Balbianello',intro:'Le promontoire mythique de Lenno.',blocks:['Construite à la fin du XVIIIe siècle sur un ancien couvent franciscain, la villa est célèbre pour sa loggia panoramique et ses tournages.']},greenway:{title:'Greenway del Lago di Como',intro:'Villages et villas à pied.',blocks:['La Greenway relie des villages de la rive ouest et permet de découvrir églises, villas, ruelles et vues sur Bellagio.']},carlotta:{title:'Villa Carlotta',intro:'Art et jardins botaniques.',blocks:['Villa Carlotta associe collections d’art, architecture aristocratique et grands jardins botaniques.']},gravedona:{title:'Gravedona',intro:'Bourg historique du haut lac.',blocks:['Gravedona offre une ambiance plus authentique que le centre du lac.']},tiglio:{title:'Santa Maria del Tiglio',intro:'Joyau roman.',blocks:['L’église est remarquable par l’alternance de pierres claires et sombres.']},piona:{title:'Abbaye de Piona',intro:'Cloître roman et silence monastique.',blocks:['L’abbaye offre une parenthèse paisible entre cloître, église, panorama et boutique monastique.']},bard:{title:'Fort de Bard',intro:'Verrou de la Vallée d’Aoste.',blocks:['Le fort contrôlait un passage stratégique et ralentit Napoléon en 1800.']},aosta:{title:'Aoste',intro:'La Rome des Alpes.',blocks:['Aoste conserve l’Arc d’Auguste, la Porta Praetoria, le théâtre romain et un centre ancien très agréable.']},gsb:{title:'Grand-Saint-Bernard',intro:'Col historique ou tunnel rapide.',blocks:['Le col offre une vraie ambiance alpine si la météo est favorable. Le tunnel est préférable en cas de fatigue.']}};
const LEXIQUE=[['Bonjour','Buongiorno','bou-on-djor-no'],['Bonsoir','Buonasera',''],['Au revoir','Arrivederci',''],['Merci beaucoup','Grazie mille',''],['S’il vous plaît','Per favore',''],['Excusez-moi','Mi scusi',''],['Je ne parle pas italien.','Non parlo italiano.',''],['Parlez-vous français ?','Parla francese?',''],['Où sont les toilettes ?','Dov’è il bagno?',''],['Avez-vous des options sans gluten ?','Avete opzioni senza glutine?',''],['Je suis cœliaque, il faut éviter toute contamination.','Sono celiaco/a, bisogna evitare qualsiasi contaminazione.',''],['À quelle heure part le prochain ferry ?','A che ora parte il prossimo traghetto?',''],['Où peut-on payer le parking ?','Dove si paga il parcheggio?',''],['Nous avons une réservation.','Abbiamo una prenotazione.','']];
